name: Self-Hosted Runner Test

on:
  push:
    branches: [ main ]

jobs:
  self-hosted-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Running on self-hosted runner!"
